### ISSUE TITLE
Context data and functionality should be clearly separated

### ISSUE THREAD

**Issue by damkjaer** [DBCDK/serviceprovider#203]
In the initial design, we decided to keep the context object as simple as possible, i.e. a json-object.
Currently it has some functionality - the call function. 
To keep in line with the original design, the call-functionality should be an independent function, which takes the context as a parameter.

**Comment by rasmuserik** [comment]
... or instead of a context, we can supply an object, which have a method to get the context, as well having the call functionality etc.? Maybe we should talk about this tomorrow.

**Comment by adamtulinius** [comment]
This appears to conflict with #192

**Comment by rasmuserik** [comment]
I think it more like a configuration-object (the pure json data),
and the context-object(oop-like object with methods).

The implementation already keeps those two apart,
but it is not clear from the usage.

In my opinion it is not a conflict.

It would be nicer though if the configuration
was a property of the object, rather than the prototype,
but that requires some rewriting. 
I'll look into that and make a pull request.

**Comment by rasmuserik** [comment]
My approach is to move the context-data-object into a data-property on the context object.

- [x] move context-data to context.data in caller.js
- [ ] update context usage in libraries.js
- [ ] update context usage in neoCoverImageTransform.js
- [ ] update context usage in neoRecommendTransform.js
- [ ] update context usage in suggest.js
- [ ] update context usage in user.js
- [ ] update context usage in neoWorkTransformer.js
- [ ] update context usage in neoSuggest.js
- [ ] update context usage in opensearchSearch.js
- [ ] update context usage in facets.js
- [ ] update context usage in Provider.js
- [ ] update context usage in search.js
- [ ] update context usage in neoOpenSearchWorkTransformer.js
- [ ] update context usage in order.js
- [ ] remove obsolete? createTest.js / genericTransformer.js or fix them for new context
