### ISSUE TITLE
/order spec: examples

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#426]
Invalid value in expire in example request: { "pids": ["870970-basis:51989252"], "library": "700401", "name": "Jens Jensen", "address": "Kirkestræde 1, 1234 Landsby", "email": "jens.jensen@example.com", "phone": "12345678", "expires": "2016-06-24T18:25:43.511Z"}. Expires should be date-format (2016-06-24)

Example response is also incorrect: { "pids": ["870970-basis:51989252"], "library": "700401", "expires": "2016-06-24T18:25:43.511Z"}. I get something like {"statusCode": 200, "data": "ok"} without "expires".

**Comment by rasmuserik** [comment]
Extra examples in spec updated with #431 

The result is still wrong, - we should decide whether to change spec, or result, or most likely both: would be nice if the result was an object, as that is more flexible when the serviceprovider is updated to support changes of orders, but the currently specified result object might not make sense, due to what openorder returns.
